server:
  port: 47076
spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://slj_househub_mysql_dd:3306/househub_user
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  instance:
    hostname: slj_househub_user_dd
  client:
    service-url:
      defaultZone: http://eurekaserver:47073/eureka
security:
  jwt:
    access: 36000000
    refresh: 2592000000
    secret: aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM